//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public Review()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int ReviewId { get; set; }
        public Nullable<System.DateTime> DateOfCreation { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string ReviewText { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual ICollection<Book> Books { get; set; }
    }
}
