//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchLog
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string QueryXml { get; set; }
    }
}
