#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace OpenAccessModel1	
{
	public partial class Product : IDataErrorInfo, INotifyPropertyChanging, INotifyPropertyChanged
	{
		private int _iD;
		[Required()]
		[Key()]
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				if(this._iD != value)
				{
					this.OnPropertyChanging("ID");
					this._iD = value;
					this.OnPropertyChanged("ID");
				}
			}
		}
		
		private int? _vendorID;
		public virtual int? VendorID
		{
			get
			{
				return this._vendorID;
			}
			set
			{
				if(this._vendorID != value)
				{
					this.OnPropertyChanging("VendorID");
					this._vendorID = value;
					this.OnPropertyChanged("VendorID");
				}
			}
		}
		
		private string _productName;
		[StringLength(200)]
		public virtual string ProductName
		{
			get
			{
				return this._productName;
			}
			set
			{
				if(this._productName != value)
				{
					this.OnPropertyChanging("ProductName");
					this._productName = value;
					this.OnPropertyChanged("ProductName");
				}
			}
		}
		
		private int? _measureID;
		public virtual int? MeasureID
		{
			get
			{
				return this._measureID;
			}
			set
			{
				if(this._measureID != value)
				{
					this.OnPropertyChanging("MeasureID");
					this._measureID = value;
					this.OnPropertyChanged("MeasureID");
				}
			}
		}
		
		private long? _basePrice;
		public virtual long? BasePrice
		{
			get
			{
				return this._basePrice;
			}
			set
			{
				if(this._basePrice != value)
				{
					this.OnPropertyChanging("BasePrice");
					this._basePrice = value;
					this.OnPropertyChanged("BasePrice");
				}
			}
		}
		
		#region IDataErrorInfo members
		
		private string error = string.Empty;
		public string Error
		{
			get
			{
				return this.error;
			}
		}
		
		public string this[string propertyName]
		{
			get
			{
				this.ValidatePropertyInternal(propertyName, ref this.error);
		
				return this.error;
			}
		}
		
		protected virtual void ValidatePropertyInternal(string propertyName, ref string error)
		{
		    this.ValidateProperty(propertyName, ref error);
		}
		
		// Please implement this method in a partial class in order to provide the error message depending on each of the properties.
		partial void ValidateProperty(string propertyName, ref string error);
		
		#endregion
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
